// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkl29vqdrRXJ7WB-J7jDjBaPHRDQ0D9o',
    appId: '1:348442686580:web:705b98d79acc2d70764d21',
    messagingSenderId: '348442686580',
    projectId: 'sign-in-d66fb',
    authDomain: 'sign-in-d66fb.firebaseapp.com',
    storageBucket: 'sign-in-d66fb.appspot.com',
    measurementId: 'G-0S430PGJ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9gkraKGTTn7I0JnLMxbp3IyBsCEbpG8s',
    appId: '1:348442686580:android:3310b0ab469d3999764d21',
    messagingSenderId: '348442686580',
    projectId: 'sign-in-d66fb',
    storageBucket: 'sign-in-d66fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY3A5a6ZhkWLtnv61Wtr0t7O1oLBH6tCE',
    appId: '1:348442686580:ios:3b6e26bd21c12e07764d21',
    messagingSenderId: '348442686580',
    projectId: 'sign-in-d66fb',
    storageBucket: 'sign-in-d66fb.appspot.com',
    iosBundleId: 'com.example.garcon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY3A5a6ZhkWLtnv61Wtr0t7O1oLBH6tCE',
    appId: '1:348442686580:ios:3b6e26bd21c12e07764d21',
    messagingSenderId: '348442686580',
    projectId: 'sign-in-d66fb',
    storageBucket: 'sign-in-d66fb.appspot.com',
    iosBundleId: 'com.example.garcon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApkl29vqdrRXJ7WB-J7jDjBaPHRDQ0D9o',
    appId: '1:348442686580:web:0a3eb655d09e5f40764d21',
    messagingSenderId: '348442686580',
    projectId: 'sign-in-d66fb',
    authDomain: 'sign-in-d66fb.firebaseapp.com',
    storageBucket: 'sign-in-d66fb.appspot.com',
    measurementId: 'G-ETW2DHV06S',
  );
}
